#!/usr/bin/env python
from droplets import main

api_token = open('api_token').read().strip()

if __name__ == '__main__':
    main(
        {'archimedean': {}}, 
        api_token=api_token,
        size='1gb',
        image='ubuntu-16-04-x64',
    )
